### ISSUE TITLE
0.8.5 broken

### ISSUE THREAD

**Issue by hheexx** [Gbuomprisco/ng2-tag-input#202]
After updating from 0.8.4:

>     ERROR in [at-loader] node_modules\ng2-tag-input\dist\modules\components\dropdown\tag-input-dropdown.component.d.ts:3:36
>         TS2305: Module '"C:/Users/Boris/Documents/Visual Studio 2015/Projects/cx_public/node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index"' has no exported member 'DropdownStateService'.
> 
>     ERROR in [at-loader] node_modules\ng2-tag-input\dist\modules\components\dropdown\tag-input-dropdown.component.d.ts:11:15
>         TS2304: Cannot find name 'Ng2Dropdown'.
> 
>     ERROR in [at-loader] node_modules\ng2-tag-input\dist\modules\components\dropdown\tag-input-dropdown.component.d.ts:30:28
>         TS2304: Cannot find name 'Ng2Dropdown'.
> 
>     ERROR in [at-loader] node_modules\ng2-tag-input\dist\modules\components\dropdown\tag-input-dropdown.component.d.ts:32:28
>         TS2304: Cannot find name 'Ng2MenuItem'.

**Comment by Gbuomprisco** [comment]
Are you running with the cli? if so, which version? thanks

**Comment by hajekj14** [comment]
We have same problem with "has no exported member 'DropdownStateService'."
tsc version: 2.0.10
angular-cli: 1.0.0-beta.19-3

downgrade to version 0.8.3 solve this.

**Comment by Gbuomprisco** [comment]
Ok, thanks. I will try solve it in the weekend 👍

**Comment by hheexx** [comment]
@Gbuomprisco 
no CLI.

Webpack@2.2.1
awesome-typescript-loader@3.0.4
ts@2.1.6

**Comment by Gbuomprisco** [comment]
Hi everyone,

could you try version 0.8.6? I have got it working with angular-cli 1.0.0-beta.32.3, and webpack 2.2.1.

**Comment by hheexx** [comment]
Can you publish it to npm?

**Comment by Gbuomprisco** [comment]
Hi @hheexx, it should be published already (under the tag `beta`)

**Comment by dland512** [comment]
I can confirm that running

`npm i ng2-tag-input@0.8.6 --save`

does install a version that fixes the issues mentioned above.

Nice control btw.

**Comment by Gbuomprisco** [comment]
Thanks! Closing issue

**Comment by Ignasimg** [comment]
seems to be broken again in 0.8.7, downgrading to 0.8.6 works fine.

**Comment by vikashk1** [comment]
Yes it is broken again in 0.8.7 :(
