### ISSUE TITLE
Install isuue

### ISSUE THREAD

**Issue by josephserrano15** [Gbuomprisco/ng2-tag-input#149]
Hello,

First of all I would like to thank you for all the hard work you have to create that awesome module. I was able to play around with few days ago, but unfortunate it has been 2 days that I am not able to start the application.

I am getting the following error message.

node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts(1,97): error TS2307: Cannot find module './dist/src/index'.

Is it something that you encounter before? I tried pretty much everything. You might have an idea for me.

Thanks again fo your work.

**Comment by josephserrano15** [comment]
I just downgraded to 0.7.0 and it is working again. Maybe the config has changed between the 2 versions. I will look further and let you know.

Thanks again

**Comment by Gbuomprisco** [comment]
Hi @josephserrano15,

Thanks very much for you congratulations, very appreciated! may I ask you which angular version are you running? I have not found this issue on my end

**Comment by josephserrano15** [comment]
Here is my config.

"dependencies": {
    "@angular/common": "~2.1.1",
    "@angular/compiler": "~2.1.1",
    "@angular/core": "~2.1.1",
    "@angular/forms": "~2.1.1",
    "@angular/http": "~2.1.1",
    "@angular/material": "^2.0.0-alpha.9-3",
    "@angular/platform-browser": "~2.1.1",
    "@angular/platform-browser-dynamic": "~2.1.1",
    "@angular/router": "~3.1.1",
    "@angular/upgrade": "~2.1.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.14",
    "@types/hammerjs": "^2.0.33",
    "angular-in-memory-web-api": "~0.1.13",
    "angular2-datatable": "^0.5.2",
    "angular2-fullcalendar": "^1.1.1",
    "angular2-google-maps": "^0.16.0",
    "bootstrap-daterangepicker": "^2.1.24",
    "core-js": "^2.4.1",
    "daterangepicker": "0.0.3",
    "font-awesome": "^4.7.0",
    "ionicons": "^3.0.0",
    "jquery": "^3.1.1",
    "jquery-daterangepicker": "^1.3.0",
    "jquery-ui": "^1.12.1",
    "lodash": "^4.17.0",
    "moment": "^2.17.0",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-ckeditor": "^1.1.5",
    "ng2-daterangepicker": "^1.0.2",
    "ng2-slideable-directive": "^1.0.13",
    "ng2-slider-component": "^1.0.9",
    "ng2-styled-directive": "^1.0.5",
    "ng2-tag-input": "^0.7.0",
    "ng2-toastr": "^1.3.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "tether": "^1.4.0",
    "zone.js": "^0.6.25"
  }

**Comment by Gbuomprisco** [comment]
I am not sure this is exactly because of it, but the component is supposed to work with Angular 2.4.2. That version will definitely not work for a number of reasons. Can you try update it? Otherwise I am afraid you will have to stick with 0.7.0 as some Angular API changed (ex. animations)

**Comment by tonysparks** [comment]
I'm receiving the same issue:

```json
  "dependencies": {
    "@angular/common": "~2.4.2",
    "@angular/compiler": "~2.4.2",
    "@angular/core": "~2.4.2",
    "@angular/forms": "~2.4.2",
    "@angular/http": "~2.4.2",
    "@angular/platform-browser": "~2.4.2",
    "@angular/platform-browser-dynamic": "~2.4.2",
    "@angular/router": "~3.1.0",    
    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.6.4",
    "bootstrap-multiselect": "^0.9.13-1",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.1",
    "ng2-bootstrap": "^1.1.16",
    "ng2-dragula": "^1.2.2",
    "ng2-tag-input": "^0.7.3",
    "rxjs": "5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
```

Error:
```
ERROR in [default] C:\Users\chq-tonys\workspace\expotr-ui\node_modules\ng2-tag-input\dist\node_modules\ng2-material-dropdown\index.d.ts:1:96
Cannot find module './dist/src/index'.
```

**Comment by Gbuomprisco** [comment]
Seems due to https://github.com/angular/angular/issues/12725

Ngc compiles stuff in node_modules

**Comment by Gbuomprisco** [comment]
Hi guys,

can you try the version 0.7.4? Thanks

**Comment by tonysparks** [comment]
Thank you @Gbuomprisco works now!

**Comment by Gbuomprisco** [comment]
Great :)
