### ISSUE TITLE
v1.3.0. references modules that can't be found

### ISSUE THREAD

**Issue by japalo** [Gbuomprisco/ng2-tag-input#422]
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
Error is thrown when upgrading to 1.3.0:
```
ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (3,26): Cannot find module ‘core’.

ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (4,35): Cannot find module ‘components’.

ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (2,26): Cannot find module ‘core’.

ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (3,27): Cannot find module ‘tag’.

ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (8,44): Cannot find module ‘core’.

ERROR in /Users/<user name>/<path to project>/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (9,62): Cannot find module ‘components’.
webpack: Failed to compile.

```
**Minimal reproduction of the problem with instructions (if applicable)**
Upgraded to latest version.

**What is the motivation / use case for changing the behavior? (if applicable)**
Something in the update messes up references. I think something is referencing old stuff.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli ^1.0.0

**ng2-tag-input version:**
1.2.8 from start, upgraded to 1.3.0

**Browser:** [all]

**Comment by Gbuomprisco** [comment]
Follow https://github.com/Gbuomprisco/ng2-tag-input/issues/419

**Comment by japalo** [comment]
Cheers! Totally missed that one. Sorry mate!

**Comment by Gbuomprisco** [comment]
No problem :)
